### ISSUE TITLE
MGRS GZD

### ISSUE THREAD

**Issue by newmanw** [trailbehind/leaflet-grids#1]
Do you have plans to show the Grid Zone Designators (GZD)?

IE: https://mappingsupport.com/p/coordinates-mgrs-google-maps.html

**Comment by andrewljohnson** [comment]
Yes, actually this is in the works now, and we coincidentally were meeting
about the project as you emailed.

It might be a couple of weeks.

**Comment by andrewljohnson** [comment]
done
